"""Initial migration

Revision ID: 88b53816f07e
Revises: 
Create Date: 2026-05-07 19:33:42.241447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b53816f07e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('trigger_reason', sa.String(length=100), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('accuracy_improvement', sa.Float(), nullable=True),
    sa.Column('training_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_model_versions_status', 'model_versions', ['status'], unique=False)
    op.create_index('ix_model_versions_version', 'model_versions', ['version'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reactants', sa.JSON(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('solvent', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reactions_created_at', 'reactions', ['created_at'], unique=False)
    op.create_index('ix_reactions_name', 'reactions', ['name'], unique=False)
    op.create_table('catalysts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('reaction_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('composition', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('activity', sa.Float(), nullable=True),
    sa.Column('selectivity', sa.Float(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structure_data', sa.JSON(), nullable=True),
    sa.Column('modification_type', sa.String(length=50), nullable=True),
    sa.Column('modification_description', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalysts_name', 'catalysts', ['name'], unique=False)
    op.create_index('ix_catalysts_reaction_id', 'catalysts', ['reaction_id'], unique=False)
    op.create_index('ix_catalysts_source', 'catalysts', ['source'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('reaction_id', sa.String(length=64), nullable=False),
    sa.Column('catalyst_id', sa.String(length=64), nullable=False),
    sa.Column('measured_activity', sa.Float(), nullable=True),
    sa.Column('measured_selectivity', sa.Float(), nullable=True),
    sa.Column('measured_stability', sa.Float(), nullable=True),
    sa.Column('yield_percentage', sa.Float(), nullable=True),
    sa.Column('predicted_activity', sa.Float(), nullable=True),
    sa.Column('predicted_selectivity', sa.Float(), nullable=True),
    sa.Column('predicted_stability', sa.Float(), nullable=True),
    sa.Column('activity_deviation', sa.Float(), nullable=True),
    sa.Column('selectivity_deviation', sa.Float(), nullable=True),
    sa.Column('stability_deviation', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('researcher_name', sa.String(length=100), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['catalyst_id'], ['catalysts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiments_catalyst_id', 'experiments', ['catalyst_id'], unique=False)
    op.create_index('ix_experiments_logged_at', 'experiments', ['logged_at'], unique=False)
    op.create_index('ix_experiments_reaction_id', 'experiments', ['reaction_id'], unique=False)
    op.create_index('ix_experiments_status', 'experiments', ['status'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('reaction_id', sa.String(length=64), nullable=False),
    sa.Column('catalyst_id', sa.String(length=64), nullable=False),
    sa.Column('activity', sa.Float(), nullable=False),
    sa.Column('selectivity', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('turnover_frequency', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=30), nullable=True),
    sa.Column('reaction_conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalyst_id'], ['catalysts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_catalyst_id', 'predictions', ['catalyst_id'], unique=False)
    op.create_index('ix_predictions_combined_score', 'predictions', ['combined_score'], unique=False)
    op.create_index('ix_predictions_reaction_id', 'predictions', ['reaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_reaction_id', table_name='predictions')
    op.drop_index('ix_predictions_combined_score', table_name='predictions')
    op.drop_index('ix_predictions_catalyst_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_experiments_status', table_name='experiments')
    op.drop_index('ix_experiments_reaction_id', table_name='experiments')
    op.drop_index('ix_experiments_logged_at', table_name='experiments')
    op.drop_index('ix_experiments_catalyst_id', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('ix_catalysts_source', table_name='catalysts')
    op.drop_index('ix_catalysts_reaction_id', table_name='catalysts')
    op.drop_index('ix_catalysts_name', table_name='catalysts')
    op.drop_table('catalysts')
    op.drop_index('ix_reactions_name', table_name='reactions')
    op.drop_index('ix_reactions_created_at', table_name='reactions')
    op.drop_table('reactions')
    op.drop_index('ix_model_versions_version', table_name='model_versions')
    op.drop_index('ix_model_versions_status', table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
